apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: adjust-liveness-probe-params-overlay
  namespace: tap-install
stringData:
  adjust-liveness-probe-params-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")

    #! makes an assumption that tap-gui is deployed in the namespace: "tap-gui"

    #@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "server", "namespace": "tap-gui"}}), expects="1+"
    ---
    spec:
      template:
        spec:
          containers:
            #@overlay/match by=overlay.subset({"name": "backstage"}),expects="1+"
            #@overlay/match-child-defaults missing_ok=True
            -
              #@overlay/remove
              readinessProbe: _
              #@overlay/remove
              livenessProbe: _
