---
tap_install:
  values:
    shared:
      ingress_domain: tap.az.tanzu.fun
      image_registry:
        project_path: tapmadesimple.azurecr.io/tap-made-simple
        username: tapmadesimple

    ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.

    profile: full # Can take iterate, build, run, view.
