---
tap_install:
  values:
    shared:
      ingress_domain: tap.tanzu.fun
      ingress_issuer: ""

      # image_registry:
      #   project_path: "SERVER-NAME/REPO-NAME"
      #   secret:
      #     name: "KP-DEFAULT-REPO-SECRET"
      #     namespace: "KP-DEFAULT-REPO-SECRET-NAMESPACE"

      # kubernetes_distribution: "K8S-DISTRO" # Only required if the distribution is OpenShift and must be used with the following kubernetes_version key.

      # kubernetes_version: "K8S-VERSION" # Required regardless of distribution when Kubernetes version is 1.25 or later.

      # ca_cert_data: | # To be passed if using custom certificates.
      #   -----BEGIN CERTIFICATE-----
      #   MIIFXzCCA0egAwIBAgIJAJYm37SFocjlMA0GCSqGSIb3DQEBDQUAMEY...
      #   -----END CERTIFICATE-----

    ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.

    #The above keys are minimum numbers of entries needed in tap-values.yaml to get a functioning TAP Full profile installation.

    #Below are the keys which may have default values set, but can be overridden.

    profile: full # Can take iterate, build, run, view.

    supply_chain: basic # Can take testing, testing_scanning.

    # ootb_supply_chain_basic: # Based on supply_chain set above, can be changed to ootb_supply_chain_testing, ootb_supply_chain_testing_scanning.
    #   registry:
    #     server: "SERVER-NAME" # Takes the value from the shared section by default, but can be overridden by setting a different value.
    #     repository: "REPO-NAME" # Takes the value from the shared section by default, but can be overridden by setting a different value.
    #   gitops:
    #     ssh_secret: "SSH-SECRET-KEY" # Takes "" as value by default; but can be overridden by setting a different value.

    # contour:
    #   envoy:
    #     service:
    #       type: LoadBalancer # This is set by default, but can be overridden by setting a different value.

    # buildservice:
    #   # Takes the value from the shared section by default, but can be overridden by setting a different value.
    #   kp_default_repository: "KP-DEFAULT-REPO"
    #   kp_default_repository_secret: # Takes the value from the shared section above by default, but can be overridden by setting a different value.
    #     name: "KP-DEFAULT-REPO-SECRET"
    #     namespace: "KP-DEFAULT-REPO-SECRET-NAMESPACE"

    tap_gui:
      metadataStoreAutoconfiguration: true # Creates a service account, the Kubernetes control plane token and the requisite app_config block to enable communications between Tanzu Application Platform GUI and SCST - Store.
      app_config:
        catalog:
          locations:
            - type: url
              target: https://github.com/pvtl-pre/tap-catalogs/blob/main/yelb-catalog/catalog-info.yaml

    # metadata_store:
    #   ns_for_export_app_cert: "MY-DEV-NAMESPACE"
    #   app_service_type: ClusterIP # Defaults to LoadBalancer. If shared.ingress_domain is set earlier, this must be set to ClusterIP.

    # scanning:
    #   metadataStore:
    #     url: "" # Configuration is moved, so set this string to empty.

    # grype:
    #   namespace: "MY-DEV-NAMESPACE"
    #   targetImagePullSecret: "TARGET-REGISTRY-CREDENTIALS-SECRET"
    #   # In a single cluster, the connection between the scanning pod and the metadata store happens inside the cluster and does not pass through ingress. This is automatically configured, you do not need to provide an ingress connection to the store.

    # policy:
    #   tuf_enabled: false # By default, TUF initialization and keyless verification are deactivated.
    # tap_telemetry:
    #   customer_entitlement_account_number: "CUSTOMER-ENTITLEMENT-ACCOUNT-NUMBER" # (Optional) Identify data for creating the Tanzu Application Platform usage reports.
