---
tap_install:
  values:
    shared:
      ingress_domain: tap.az.tanzu.fun

      image_registry:
        project_path: tapmadesimple.azurecr.io/tap-made-simple
        username: tapmadesimple

      kubernetes_version: 1.25.0 # Required regardless of distribution when Kubernetes version is 1.25 or later.

    ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.

    profile: full # Can take iterate, build, run, view.

    tap_gui:
      service_type: ClusterIP # If the shared.ingress_domain is set as earlier, this must be set to ClusterIP.
      metadataStoreAutoconfiguration: true # Creates a service account, the Kubernetes control plane token and the requisite app_config block to enable communications between Tanzu Application Platform GUI and SCST - Store.

    metadata_store:
      ns_for_export_app_cert: "default"
      app_service_type: ClusterIP # Defaults to LoadBalancer. If shared.ingress_domain is set earlier, this must be set to ClusterIP.

    package_overlays:
      - name: tap-gui
        secrets:
          - name: adjust-liveness-probe-params-overlay
