---
tap_install:
  values:
    shared:
      ingress_domain: tap.az.tanzu.fun

      image_registry:
        project_path: tapmadesimple.azurecr.io/tap-made-simple
        username: tapmadesimple

      kubernetes_version: 1.25.0 # Required regardless of distribution when Kubernetes version is 1.25 or later.

    ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.

    profile: full # Can take iterate, build, run, view.

    contour:
      envoy:
        service:
          type: LoadBalancer # This is set by default, but can be overridden by setting a different value.

    tap_gui:
      metadataStoreAutoconfiguration: true # Creates a service account, the Kubernetes control plane token and the requisite app_config block to enable communications between Tanzu Application Platform GUI and SCST - Store.
      app_config:
        auth:
          allowGuestAccess: true
        catalog:
          locations:
            - type: url
              target: https://github.com/pvtl-pre/tap-catalogs/blob/main/yelb-catalog/catalog-info.yaml

    metadata_store:
      ns_for_export_app_cert: "default"
      app_service_type: ClusterIP # Defaults to LoadBalancer. If shared.ingress_domain is set earlier, this must be set to ClusterIP.
